# __forward_decs__:
- target
- target2
- target3

- target:
    - src:
        - 'MANTIS-EPS/src/mantis.c'
        - 'MANTIS-EPS/src/main.c'
    - inc:
        - 'MANTIS-EPS/inc/**/*.h'

- target2:
  - src: 
    - 'MANTIS-EPS/src/root.c'
    - 'MANTIS-EPS/src/main.c'

  - inc:
    - 'MANTIS-EPS/inc/**/*.h'

  - dep:
    - target3

- target3:
  - src: 
    - 'MANTIS-EPS/src/root.c'
    - 'MANTIS-EPS/src/main.c'

  - inc:
    - 'MANTIS-EPS/inc/**/*.h'
